// initial state
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'

// post actions
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'

// comment actions
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'

// ajax status
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

// voting actions
export const VOTE_UP_SUCCESS = 'VOTE_UP_SUCCESS'
export const VOTE_DOWN_SUCCESS = 'VOTE_DOWN_SUCCESS'